[package]
name = "lazy-reach"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.28.0"
minilp = "0.2.2"
num-traits = "0.2.14"